### ISSUE TITLE
LDFlagValue TypeScript type should be `unknown`

### ISSUE THREAD

**Issue by LiamGoodacre** [launchdarkly/js-sdk-common#16]
**Describe the bug**
The `LDFlagValue` type is currently `any`, but shouldn't it be `unknown`?
```diff
-export type LDFlagValue = any;
+export type LDFlagValue = unknown;
```
Feel free to ignore if you disagree.

**To reproduce** N/A
**Expected behavior** N/A
**Logs** N/A
**SDK version** 2.13.0
**Language version, developer tools** TypeScript
**OS/platform** N/A
**Additional context** N/A

**Comment by eli-darkly** [comment]
It'd be helpful if you could say more about why this is a concern.

As I understand it, the distinction between `any` and `unknown` is that the compiler is more restrictive about implicit casting. Since there's only a single `variation` and `variationDetail` method (unlike the strongly typed LaunchDarkly SDKs which have `boolVariation`, etc.) I believe that if the type were `unknown`, application code would have to do an explicit cast every time it evaluated a flag. It's unclear to me what the benefit of this would be.

In any case, I don't think we can change the type at this point without it being a potentially breaking change that requires a new major version.

**Comment by LiamGoodacre** [comment]
Yes, it would be breaking, and would require user validation/casts (I see this as a benefit, the fewer `any`s the better).  It's no real issue, just thought I'd raise it to see if it was intentional/wanted/etc :)

**Comment by eli-darkly** [comment]
It's intentional in the sense that if we're only going to have a single `variation` method, we want it to be convenient to use, and having to check the type every single time you evaluate a flag does not make for a seamless feature flag experience (it's common in feature-flagged apps to have these evaluation calls all over the place, embedded within complex expressions, etc.). So all of our loosely-typed SDKs (client-side JS, Node.JS, Ruby, Python) use this approach.

If this is a concern, we would probably prefer to go the same route that we've done in the strongly typed SDKs: provide `boolVariation`, `stringVariation`, etc. so that it's the SDK that has to do the type checking, and the application developer can just freely use feature flag values as needed (the behavior if the type is wrong would be the same as in the strongly-typed SDKs: you just receive the fallback value that you provided as the last parameter to the method, which would have to be of the right type). That would also have the advantage of being backward-compatible since people could still use the old `variation` method.

**Comment by codeBelt** [comment]
I just started using launchdarkly today but I think the following would work: 

```diff
-export type LDFlagValue = any;

+export type LDFlagValue = boolean | number | string | undefined;
```

Not sure if a `LDFlagValue` can be a `string` so you can remove that if you cannot.

**Comment by eli-darkly** [comment]
@codeBelt A flag value can be any of the JavaScript types that correspond to a JSON type. So, if it's not null/undefined, it can be a boolean, number, string, array, or object.

**Comment by odell-allstripes** [comment]
For me the `any` is not a problem, like you said @eli-darkly it could be any JSON type so `any` is fairly accurate.

I think the problem referenced in #32 is more relevant though. While each named flag could have any value, the index signature on `LDFlagSet` allows _every string key to have an `any` value_. That allows for typos in the code and makes it more difficult to remove a flag from the codebase once it's been archived.

**Comment by eli-darkly** [comment]
@odell-allstripes I'm not sure I understand your meaning here:

> While each named flag could have any value, the index signature on LDFlagSet allows every string key to have an any value. That allows for typos in the code and makes it more difficult to remove a flag from the codebase once it's been archived.

Can you give an example of the kind of problem you're thinking of?

If your point is just that LDFlagSet is defined in a general way, rather than having specific property names `myFirstFlagKey`, `myOtherFlagKey`, etc. that correspond to specific flags you've created... well, yes, but I can't see how it could possibly work any other way. There is no way for us to know what flag keys an application may be using and embed those into this type definition. So I'm not sure what you have in mind.

**Comment by eli-darkly** [comment]
And keep in mind that it's very common for applications to use the `variation` method to evaluate flags one at a time, rather than calling `allFlags`; I think the latter is a relatively unusual way to use the SDK (mainly because you will not get any analytics events if you do that). And the flag key parameter to `variation` is simply a string. So it's never really been practical to rely on compile-time checking of property names to ensure that you're not referencing any misspelled or obsolete flag keys; that's just as true for the strongly-typed SDKs like Go and Java as it is for JS/Node.

**Comment by odell-allstripes** [comment]
> Can you give an example of the kind of problem you're thinking of?

In particular I'm using the React SDK but I imagine the problems I'm facing show up in other JS settings too. While I can get IDE autocomplete for flags by extending `LDFlagSet` in my own declaration file, I can't remove the index signature, so TS allows me to access flags that don't exist (they have a value of `any`). So this is the typo problem, if I have a flag called `myFirstFlagKey` TS won't complain if I instead access `myFirsFlagKey`.

The second issue is removing references to flags once they are archived or once product agrees we no longer intend to use them. What I would like to do is remove them from my `LDFlagSet` interface, and have TS call out every file that is still accessing them. What happens instead is that removing them from the interface switches them back to `any` value, and TS does not complain.

> And the flag key parameter to variation is simply a string.

What if the `LDClientBase` interface was generic, with a default type of `LDFlagSet`, like:
```
interface LDClientBase<ClientFlagSet = LDFlagSet> {
    identify(user: LDUser, hash?: string, onDone?: (err: Error | null, flags: ClientFlagSet | null) => void): Promise<ClientFlagSet>;

    variation(key: keyof ClientFlagSet, defaultValue?: LDFlagValue): LDFlagValue;
}
```

Since the React SDK has a layer of indirection due to `useContext`, I'm not sure if this change would be particularly useful there. But I think it should still open the door to a more flexible typing, because `LDContext` could then be generic, and all consumer hooks might have the same option:
```
interface LDContext<ClientFlagSet> {
  flags: ClientFlagSet;
  ldClient?: LDClient<ClientFlagSet>;
}
```
