### ISSUE TITLE
uuid package needs upgrade to version 7+ 

### ISSUE THREAD

**Issue by troymjones** [launchdarkly/js-sdk-common#46]
Getting this warning when install launchdarkly/js-sdk-common because of an out-of-date uuid version

`npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.`

**Comment by bwoskow-ld** [comment]
Thanks for pointing this out. We'll take a look.

_Filed internally as 119528._

**Comment by CaptainMaxD** [comment]
Tengo la misma cuestión. Gracias por preguntar.

**Comment by eddiemonge** [comment]
This is fixed in the 4.x releases. It is incorrectly tagged in the `prepare 3.5.1 release` commit. That commit does not fix this issue. This will also need to be updated in https://github.com/launchdarkly/js-sdk-common

**Comment by eli-darkly** [comment]
@eddiemonge:

We're aware that it is not fixed in 3.x. The tag you're seeing there is not really from us, it's a GitHub mistake that was enabled by a process mistake on our part: that is, GitHub does not understand that issue/PR numbers in commit messages from our private development repo do not refer to issues in this repo, which is why we normally squash-merge those PRs to avoid dumping all those inapplicable commit messages into this repo, but it looks like we did a regular merge on that one and now there's no way to remove those inapplicable links.

Anyway... the reason we haven't yet fixed this in the version that is used by js-client-sdk is that there is a browser compatibility issue we need to make a decision on. Later versions of `uuid` rely on the `Crypto.getRandomValues()` API, which is not available in some browsers we have up till now been compatible with. So if we start using it, we are imposing a new requirement for some customers to install a polyfill. We normally try to avoid doing that within the same major version of js-client-sdk.

**Comment by louis-launchdarkly** [comment]
Closing out the loop on this - as Eli explained, we are not going to impose the new requirement on a minor version release. If anyone is using this package directly, we recommend using 4.x or 5.x to get the uuid fix. In case you are using the JS Client SDK, the latest 3.x of the JS Client SDK is using 5.x of this package and has the fix in it.
